### ISSUE TITLE
Creating/Updating keys doesn't work in AEM 6.5 due to "checkbox.show is not a function"

### ISSUE THREAD

**Issue by pcastelog** [orbinson/aem-dictionary-translator#231]
**Steps to reproduce**

1. Create a new dictionary
2. Open it
3. Click on "Create key" --> A JS error appears on the console
4. Click again
5. The dialog appears, enter the data, and click on create. Nothing happens

`dictionary.js:157 Uncaught TypeError: checkbox.show is not a function
    at showHideCheckbox (dictionary.js:157:22)
    at showHideCheckboxForElement (dictionary.js:144:13)
    at HTMLInputElement.<anonymous> (dictionary.js:131:13)
    at jQuery.each (jquery.js:371:19)
    at jQuery.fn.init.each (jquery.js:137:17)
    at HTMLDocument.<anonymous> (dictionary.js:130:57)
    at HTMLDocument.dispatch (jquery.js:5232:27)
    at elemData.handle (jquery.js:4884:28)
    at Object.trigger (jquery.js:5136:12)
    at HTMLElement.<anonymous> (jquery.js:5866:17)`

**Tested in** 
1. Vanilla AEM 6.5.23
2. Translator version 1.5.0

**Comment by kwin** [comment]
@pcastelog Can you come up with a PR?

**Comment by kwin** [comment]
I can reproduce but only with AEM 6.5 (not with AEMaaCS), I am investigating now....
